---
- name: Create requirements
  block:
    - name: Create docker network for all services
      community.docker.docker_network:
        name: "{{ server_network_name }}"

    - name: Create docker volume to store the certificates
      community.docker.docker_volume:
        name: traefik_public_certificates

    - name: Create directory for traefik access logs
      become: true
      ansible.builtin.file:
        path: /var/log/traefik
        state: directory
        mode: "0644"

    - name: Create logrotate conf
      become: true
      ansible.builtin.copy:
        src: ./traefik.logrotate.conf
        dest: /etc/logrotate.d/traefik
        mode: "0644"

- name: Run Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/log/traefik:/var/log:rw"
      - "traefik_volume_certificates:/certificates:rw"
    ports:
      "{{ ['80:80'] if ansible_host == vodomat_server_hostname else ['80:80', '443:443'] }}"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.le.acme.email={{ email }}"
      - "--certificatesresolvers.le.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/access.log"
      - "--log"
