---
- name: Create docker network for all services
  community.docker.docker_network:
    name: "{{ server_network_name }}"

- name: Create access.log file for Traefik
  ansible.builtin.file:
    path: "/home/{{ sudo_user }}/access.log"
    state: touch
    mode: "0664"

- name: Run Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/{{ sudo_user }}/access.log:/var/log/access.log:rw"
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/access.log"
