---
- name: Deploy server
  hosts: hub
  roles:
    # Preconfig
    - role: preconfig
      tags: preconfig
    # Run reverse-proxy
    - role: run_proxy
      tags: run_proxy
    # Deploy Vodomat Server API
    - role: deploy_service
      deploy_service_name: vodomat_api
      tags: [deploy_api, deploy_all]
    # Deploy Vodomat Server Admin
    - role: deploy_service
      deploy_service_name: vodomat_server_admin
      tags: [deploy_server_admin, deploy_all]
