---
- name: Deploy server
  hosts: server
  roles:
    # Preconfig
    - role: preconfig
      tags: preconfig
    # Deploy Vodomat Server
    - role: deploy_service
      service_name: vodomat_server
      tags: [deploy_server, deploy_all]
    # Deploy Vodomat Server API
#    - role: deploy_service
#      service_name: api
#      tags: [deploy_api, deploy_all]
    # Deploy Vodomat Server Admin
#    - role: deploy_service
#      service_name: server_admin
#      tags: [deploy_server_admin, deploy_all]