---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: init_cluster
      tags: collect_cluster
    - role: build
      build_service_name: vodomat_server
      build_service_tag: latest
      tags: build_server
    - role: build
      build_service_name: vodomat_server_admin
      build_service_tag: latest
      tags: build_server_admin
    - role: deploy
      deploy_service_name: redis
      deploy_service_tag: latest
      tags: deploy_redis

- name: Manager servers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: join_cluster
      tags: collect_cluster
