---
- name: Deploy server
  hosts: server
  roles:
    # Preconfig
    - role: preconfig
      tags: preconfig
    # Run reverse-proxy
    - role: run_proxy
      tags: run_proxy
    # Deploy Vodomat Server
    - role: deploy_service
      deploy_service_name: vodomat_server
      tags: [deploy_server]
