---
- name: "[vodomat_api] Run service container(s)"
  community.docker.docker_container:
    name: vodomat_api
    image: "vodomat_api:{{ vodomat_api_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    env_file: "{{ path_to_env_file }}"
    labels:
      traefik.enable=true
      traefik.http.routers.vodomat_api-http.rule=Host(`"{{ api_url }}"`)
      traefik.http.routers.vodomat_api-http.entrypoints=http
      {% if production %}
      traefik.http.routers.vodomat_api-https.rule=Host(`"{{ api_url }}"`)
      traefik.http.routers.vodomat_api-https.entrypoints=https
      traefik.http.routers.vodomat_api-https.tls=true
      traefik.http.routers.vodomat_api-https.tls.certresolver=le
      traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      traefik.http.routers.vodomat_api-http.middlewares=https-redirect
      {% endif %}
