---
- name: "[vodomat-pay_api] Run service container"
  community.docker.docker_container:
    name: vodomat_pay_api
    image: "vodomat_pay_api:{{ vodomat_pay_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    volumes:
      - "/home/{{ sudo_user }}/{{ portmone_orders_dir }}:/opt/api/{{ portmone_orders_dir }}"
    env_file: "{{ path_to_env_file }}"
    env:
      TZ: "{{ timezone }}"
#      FLASK_DEBUG: "true"
  when: deploy_service_postfix == "_api"

- name: "[vodomat-pay_frontend] Run service container"
  community.docker.docker_container:
    name: vodomat_pay_frontend
    image: "vodomat_pay_frontend:{{ vodomat_pay_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    env:
      TZ: "{{ timezone }}"
    labels:
      traefik.enable=true
      traefik.http.routers.vodomat_pay-http.rule=Host(`"{{ app_url }}"`)
      traefik.http.routers.vodomat_pay-http.entrypoints=http
      {% if production %}
      traefik.http.routers.vodomat_pay-https.rule=Host(`"{{ app_url }}"`)
      traefik.http.routers.vodomat_pay-https.entrypoints=https
      traefik.http.routers.vodomat_pay-https.tls=true
      traefik.http.routers.vodomat_pay-https.tls.certresolver=le
      traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      traefik.http.routers.vodomat_pay-http.middlewares=https-redirect
      {% endif %}
  when: deploy_service_postfix == "_frontend"