galaxy_info:
  role_name: init_cluster
  description: Init Swarm cluster
  author: Evgeniy Buhaiov
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
