---
- name: "[vodomat_server] Run service container(s)"
  community.docker.docker_container:
    name: "vodomat_server"
    image: "vodomat_server:{{ vodomat_server_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    env_file: "{{ path_to_env_file }}"
    env:
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vodomat_server-http.rule: >-
        Host(`{{ server_url }}`) || Host(`{{ secondary_server_url }}`)
      traefik.http.services.vodomat_server.loadbalancer.server.port: "{{ server_port | string }}"
      traefik.http.routers.vodomat_server-http.entrypoints: "http"

- name: Delete old rows from some tables
  block:
    - name: Create script for delete old rows
      ansible.builtin.template:
        src: "./delete_old_data.py.j2"
        dest: "/home/{{ sudo_user }}/delete_old_data.py"
        owner: "{{ sudo_user }}"
        mode: "0700"

    - name: Add script to cron
      ansible.builtin.cron:
        name: "Delete old rows"
        minute: "0"
        hour: "3"
        job: "/home/{{ sudo_user }}/delete_old_data.py"
        user: "{{ sudo_user }}"
