---
- name: "[vodomat_server] Run service container(s)"
  community.docker.docker_container:
    name: "vodomat_server-{{ item }}"
    image: "vodomat_server:{{ vodomat_server_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    env_file: "{{ path_to_env_file }}"
    labels:
      traefik.enable=true
      traefik.http.routers.vodomat_server-http.rule=Host(`"{{ server_url }}"`)
      traefik.http.services.vodomat_server.loadbalancer.server.port="{{ server_port }}"
      traefik.http.routers.vodomat_server-http.entrypoints=http
  with_sequence: start=0 count={{ server_container_count }}
