---
- name: "[vodomat_server] Run service container(s)"
  community.docker.docker_container:
    name: "vodomat_server-{{ item }}"
    image: "vodomat_server:{{ vodomat_server_image_tag }}"
    restart_policy: always
    networks:
      - name: "{{ server_network_name }}"
    env:
      APP_PORT: "{{ item }}"
    env_file: "{{ path_to_env_file }}"
  with_sequence: start=0 count={{ server_container_count }}
