---
- name: "[{{ deploy_service_name }}] Configure secret"
  ansible.builtin.include_tasks: "../secret.yml"

- name: "[{{ deploy_service_name }}] Deploy service"
  community.docker.docker_swarm_service:
    name: "{{ deploy_service_name }}"
    image: "{{ registry_name }}/{{ deploy_service_name }}:{{ deploy_service_tag }}"
    state: present
    networks:
      - name: "{{ server_network_name }}"
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 8080
        target_port: 8080
    secrets:
      - secret_name: "{{ deploy_service_name }}.env"
        filename: "/opt/server/vodomat_server.yml"
