---
sudo_user: jerrye

server_network_name: server_network

vodomat_server_image_tag: "{{ hostvars['vodomat_server']['ansible_facts']['vodomat_server_image_tag'] }}"
vodomat_api_image_tag: "{{ hostvars['vodomat_server']['ansible_facts']['vodomat_api_image_tag'] }}"
vodomat_server_admin_image_tag: "{{ hostvars['vodomat_server']['ansible_facts']['vodomat_server_admin_image_tag'] }}"

github_url_base: git@github.com:ebugaiov
