---
- name: "[{{ deploy_service_name }}] Configure secret"
  block:
    - name: "[{{ deploy_service_name }}] Create secret"
      ansible.builtin.include_tasks: "create_secret.yml"

  rescue:
    - name: "[{{ deploy_service_name }}] Delete service"
      community.docker.docker_swarm_service:
        name: "{{ deploy_service_name }}"
        state: absent
    - name: "[{{ deploy_service_name }}] Create secret"
      ansible.builtin.include_tasks: "create_secret.yml"
