---
- name: Setup ufw for docker-swarm
  become: true
  block:
    - name: Open tcp ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: [22, 2377, 7946]

    - name: Open udp ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      loop: [4789, 7946]

    - name: Enable ufw
      community.general.ufw:
        state: enabled

- name: Install Docker
  become: true
  block:
    - name: Add universe repo
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        update_cache: true
        cache_valid_time: 86400

    - name: Add dockers key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Install stable dockers repo
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        update-cache: true
        filename: docker

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        update-cache: true

    - name: Check Docker installed and restarted
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Install Docker Compose
  become: true
  block:
    - name: Get last version of docker-compose
      ansible.builtin.uri:
        url: "https://api.github.com/repos/docker/compose/releases/latest"
        body_format: json
      register: page

    - name: Install docker-compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

- name: Install additional python packages
  block:
    - name: Install pips packages
      ansible.builtin.pip:
        name: docker

- name: Completion installation
  become: true
  block:
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Reboot instances
      ansible.builtin.reboot:
