---
- name: Setup ufw
  become: true
  block:
    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Open SSH port (TCP 22)
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable ufw
      community.general.ufw:
        state: enabled

- name: Install Docker
  become: true
  block:
    - name: Add universe repo
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
          - python3-dev
          - default-libmysqlclient-dev
          - build-essential
          - pkg-config
        update_cache: true
        cache_valid_time: 86400

    - name: Add dockers key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Install stable dockers repo
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        update-cache: true
        filename: docker

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        update-cache: true

    - name: Check Docker installed and restarted
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Install additional python packages
  block:
    - name: Install pips packages
      ansible.builtin.pip:
        name:
          - docker
          - mysqlclient

- name: Completion installation
  become: true
  block:
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Reboot instances
      ansible.builtin.reboot:
