galaxy_info:
  role_name: deploy_sevice
  description: Build image and Deploy service
  author: Evgeniy Bugaiov
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
